### ISSUE TITLE
Please provide systemd service file

### ISSUE THREAD

**Issue by hb9eue** [kou/milter-greylist#2]
Hi

Nowadays most linux distros have moved from sysv to systemd.

milter-greylist still comes with sysv init scripts to which systemd builds a wrapper.

For whatever reasong the pidfile: comment is not being recognized, preventing systemd to be able to respawn milter-greylist on crash.

Would it be possible to provide a propper systemd service file?

**Comment by kou** [comment]
Ah, this is just an old mirror.
Could you report it to the upstream?
http://hcpnet.free.fr/milter-greylist/
